# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EVA-Voice-Coach

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ef04d04ae76423185a188df891f5cda }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1a1bcc4afc0c49beb98448730b852e6e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ef04d04ae76423185a188df891f5cda }}/mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EVA-Voice-Coach'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3e4320df4be148858504ffe0291de2c7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ef04d04ae76423185a188df891f5cda }}/mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}'